<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>$(IosTargetFrameworks);$(AndroidTargetFrameworks)</TargetFrameworks>
        <Description>Shiny Push Integration - Google Firebase Cloud Messaging</Description>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('-ios'))">
        <ProjectReference Include="..\Shiny.Firebase.iOS.Binding\Shiny.Firebase.iOS.Binding.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Shiny.Push"/>
    </ItemGroup>
</Project>