name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches:
    - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
          dotnet-version: '10.0.x'
          workloads: maui-ios, maui-android
      
    - name: Resolve SPM Dependencies
      run: |
        xcodebuild -project firebase_ios/native/shinyfirebase/ShinyFirebase.xcodeproj -scheme ShinyFirebase -resolvePackageDependencies
        xcodebuild -project firebase_ios/native/firestore/ShinyFirebaseFirestore.xcodeproj -scheme ShinyFirebaseFirestore -resolvePackageDependencies

    - name: Build
      run: dotnet build Firebase.slnx /restore -m -property:Configuration=Release -property:PublicRelease=true

    - name: Post NuGet Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-artifacts
        path: '**/*.nupkg'

    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nugets
        path: ${{ github.workspace }}/artifacts
        retention-days: 5

    - name: Publish NuGets
      if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/v') }}
      run: dotnet nuget push ./**/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }} --skip-duplicate
